### ISSUE TITLE
[Suggestion] Make a server-side-only version

### ISSUE THREAD

**Issue by SyberiaK** [Kira-NT/nether-chest#6]
I'm making a Fabric server and i wanted this mod to be server-side-only so my friends can connect and play on vanilla
Maybe Polymer will be useful for you

**Comment by Kira-NT** [comment]
I'm not interested in implementing this one, to be quite frankly honest with you. This is my hobby, not a paid job, therefore I'm doing things I see a good reason for. And this one is just not the case - most mods that add new blocks are both client- and server-side, so if somebody tries to make a nice modpack, there will be a lot of mods that players should install on their end too. So I don't really see why Nether Chest should be different. Moving on, I wouldn't even accept a PR that does all the work for me, because I don't wanna see this mod being heavily dependent on some third party "core library"
