### ISSUE TITLE
Bundles as keys, NBT, and names

### ISSUE THREAD

**Issue by allanonmage** [Kira-NT/nether-chest#8]
Working with this on a 1.19.2 Fabric server.

I used an empty bundle as a key, loaded some stuff to the nether chest, then renamed it.  Putting it back on the key slot, I couldn't get my stuff.  Another empty bundle could not get to it either(!).  I found the setting to turn off NBT, and that worked.  I can get to the stuff, and use a named bundle empty bundle, or a full bundle to get to the stuff.

However, I'm not following why other unnamed bundles wouldn't work, and I was wondering if there was a way to turn off the precise NBT match, but still keep a name option for a key.

So far, the primary use-case I can think of for this chest is a mobile shop, so each of the keys need to be common enough to not lose or easily replace, but special enough that they remain as keys in the default slot of the Nether Chest.  In this scenario, it's highly likely someone will forget a key in the slot of a particular Nether chest, thus removing it from the default slot, and since we have waystones and the nether chest is a common loot drop, there's no telling how far out in what dimension that might be.  Or it could be in a long forgotten cave somewhere, or at the end of the end where the player needed to seppuku to get back to spawn.

**Comment by Kira-NT** [comment]
I haven't encountered any issues with bundles on my end. The issue you're experiencing could be related to using an unnamed, empty bundle as a key, then attempting to access your data via another re-unnamed, empty bundle (or vice versa). Please note that if you've previously named a bundle and then removed the name with a space (" ") via an anvil, it won't be considered a brand-new object untouched by an anvil.

Moreover, a datapack or mod you use to craft bundles might attach some custom NBT data to them, causing this issue.

Regardless, implementing an option for "loose" NBT comparison might be beneficial, given that it's fairly common for two objects, seemingly identical from a user's standpoint, to differ. A prime example is a brand-new shulker box versus one that has been used to store items at some point.

**Comment by Kira-NT** [comment]
I finally got around to updating my mods, including this one. Once again, bundles are no different from other items. The reason another empty bundle didn't point to the same channel, as you yourself had demonstrated, is that one of them had extra NBT entry(ies). I provided examples of how this could have happened in my previous message.

Also, I have decided against introducing a "loose comparison" option, as it has no clear definition. Therefore, its implementation is destined to be highly opinionated, which I would like to avoid.

Thus, since there's no bug to fix and no feature to implement, I'm closing the issue.
